### ISSUE TITLE
Question regarding Arabic transcripte support

### ISSUE THREAD

**Issue by mostafa-kenawey** [srvk/eesen-transcriber#10]
After long time of investigation and searching for transcriber for Arabic audios, my investigation doesn't come back with a any promising solution.
But after i tried your library for transcribing English with that great results i was wondering how can i make modifications for supporting other language than English.
And while i'm not a researcher and i have poor experience in transcribing and speech processing, i thought you can help me by giving some hints or documents about how to transcribe Arabic audio, or just any useful resources could help me.

Thanks

**Comment by mostafa-kenawey** [comment]
@riebling , Any recommendations here please ?

**Comment by fmetze** [comment]
It should be possible to adapt the recipe described in https://groups.csail.mit.edu/sls/publications/2014/Dehak_SLT-2014.pdf https://groups.csail.mit.edu/sls/publications/2014/Dehak_SLT-2014.pdf to Eesen with little effort, and train an Arabic Eesen system. The recipe is distributed along with Kaldi, the data however may not be publicly available (and this is unfortunately nothing that we can help with); not sure if there are “open” Arabic resources. Once you have the Arabic Eesen system, it is easy to integrate it into the transcriber system. 

> On Jun 15, 2016, at 4:24 AM, Mostafa R. Arafa notifications@github.com wrote:
> 
> @riebling https://github.com/riebling , Any recommendations here please ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub https://github.com/srvk/eesen-transcriber/issues/10#issuecomment-226120888, or mute the thread https://github.com/notifications/unsubscribe/AEnA8ec9GtSg1O2mo9N3-lEnmHi5G2EAks5qL7augaJpZM4Iy3NU.

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by mostafa-kenawey** [comment]
Thank you, It's a bit clear.
I'll follow Kaldi doc, hopefully i can.
