### ISSUE TITLE
AMI in US-East?

### ISSUE THREAD

**Issue by rightfront** [srvk/eesen-transcriber#2]
I'm confined to using US-East region for EC2, any chance on getting the AMI copied there?

(I'd do it myself, but I don't have permissions...)

**Comment by riebling** [comment]
Seems like a fine idea. This AMI is now public in us-east (N. Virginia):

   ami-5a210a30    EESEN-train-transcribe-V2

On 02/08/2016 03:18 PM, rightfront wrote:

> I'm confined to using US-East region for EC2, any chance on getting the AMI copied there?
> 
> (I'd do it myself, but I don't have permissions)
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/2.

## 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by rightfront** [comment]
Thanks!
