### ISSUE TITLE
Unify Vagrantfiles

### ISSUE THREAD

**Issue by fmetze** [srvk/eesen-transcriber#23]
Would it be possible to unify the two vagrant files (aspire and not aspire one)?

Maybe have only one Vagrant file, which then calls a shared script (or executes a shared code block), and then two separate scripts.

Similarly, with the Makefiles - would it be possible to keep one main Makefile, with two "wrapper" makefiles around them? The shared "main" Makefile would maybe do all the pre-processing and other shared stuff?

**Comment by riebling** [comment]
For Makefiles, having just run the Aspire one, certainly! There's already conditional `ifeq` blocks to handle 3 cases: Tensorflow vs. Aspire vs. Tedlium models, the goal being to have only one Makefile.

Same can be done with the Vagrantfile, sure. (One big difference, for example, is that Aspire requires installing Kaldi)
