### ISSUE TITLE
8khz switchboard models

### ISSUE THREAD

**Issue by wmcmurtry** [srvk/eesen-transcriber#26]
Hello,

I want to use the 8khz switchboard models. I am using the EESEN toolkit.

In the Makefile we have:
      # optionally get 8khz models
      if [ -f /vagrant/swbd-v1-pitch.tgz ]
      then
         cd /home/${user}/eesen/asr_egs/swbd
         tar zxvf /vagrant/swbd-v1-pitch.tgz
      fi

What is in the file swbd-v1-pitch.tgz? Is it some combination of these three LDC97S62 LDC2002S09 LDC2002T43? Or something else? (I have a LDC subscription.)

If we have the .tgz file set up correctly, then are additional steps required to use the 8khz swbd model other than changing Makefile.options?

Thank you

**Comment by fmetze** [comment]
Hi, yes, the contents of this folder are a model trained with ease on the switchboard dataset. If you are an LDC subscriber, we’ll be happy to share it with you directly.

**Comment by wmcmurtry** [comment]
Resolved!
