### ISSUE TITLE
default: virtual memory exhausted: Cannot allocate memory

### ISSUE THREAD

**Issue by aolney** [srvk/eesen-transcriber#27]
Seems to occur when using the default Vagrantfile with bento/ubuntu-16.04 (i.e., compiling kaldi by default). 

Increasing RAM to 32GB didn't seem to help, but increasing the swap size did [ [link](https://superuser.com/questions/1058491/is-it-possible-to-create-a-swap-file-for-a-linux-guest-vm-managed-by-vagrant) ].

Specifically

```
  config.vm.provision "shell", inline: <<-SHELL
	#add virtual memory
	sudo apt install swapspace -y
```

**Comment by aolney** [comment]
Even better (or perhaps alternately) replace `make -j` with ``make -j`nproc` `` in the Vagrantfile

**Comment by fmetze** [comment]
added as an option
