### ISSUE TITLE
align.sh doesn't copy stm file to build/output

### ISSUE THREAD

**Issue by aolney** [srvk/eesen-transcriber#30]
The [user guide for word alignment](https://github.com/srvk/eesen-transcriber/blob/master/USERGUIDE.md#word-level-alignments) does not currently work because the `.stm` file in `/vagrant` is not copied to `build/output`

To fix this, this line in `align.sh`
```
cp $dirname/$basename.stm build/output/
```
should be this
```
cp $dirname/$basename.stm $dirname/build/output/
```

**Comment by fmetze** [comment]
fixed, thanks
