### ISSUE TITLE
Clean up instructions

### ISSUE THREAD

**Issue by fmetze** [srvk/eesen-transcriber#4]
There are 3 READMEs - which one is really needed?

**Comment by riebling** [comment]
And so what did I do, but add a fourth one(!) for licensing. How about we adopt a style that supports two?:
1. [README.md](https://github.com/srvk/eesen-transcriber/blob/master/README.md) which appears on the repository main page by default.. a short overview. 
2. One other, which can grow to be arbitrarily large, having chapters devoted to various topics: quickstart, detailed usage, license information

**Comment by riebling** [comment]
And now I see why there were multiple READMEs. Some contain transcriptions of system output, and would require major scrolling to get to next chapters.  If there are more than one such transcript, a single big README might be unmanageable to read from anywhere but an editor. Ideas:
1. Don't include transcripts, make them separate files - But where? 
   a) I used to keep these as attached files on speechkitchen.org pages.
   b) Perhaps the most similar techique would place them on the GitHub repository wiki
2. Let README be big, and if people want to see past trasncripts, they can use an editor
3. Ideas?

**Comment by fmetze** [comment]
i think i like the idea of having a single README.md in the home of the repository which explains the fundamentals, then a License.md for legals, but all the other stuff moves into a wiki?

> On Mar 24, 2016, at 2:04 AM, riebling notifications@github.com wrote:
> 
> And now I see why there were multiple READMEs. Some contain transcriptions of system output, and would require major scrolling to get to next chapters. If there are more than one such transcript, a single big README might be unmanageable to read from anywhere but an editor. Ideas:
> 1. Don't include transcripts, make them separate files - But where? 
> a) I used to keep these as attached files on speechkitchen.org pages.
> b) Perhaps the most similar techique would place them on the GitHub repository wiki
> 2. Let README be big, and if people want to see past trasncripts, they can use an editor
> 3. Ideas?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/4#issuecomment-200469188

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by riebling** [comment]
I think we've sufficiently cleaned these up, so closing #4
