### ISSUE TITLE
Lexicon expansion

### ISSUE THREAD

**Issue by fmetze** [srvk/eesen-transcriber#7]
What are we doing with new words in the re-train the language model section? I.e. if I am adding new words with the new training text?

Can we add those words to the pronunciation dictionary either manually and/ or automatically?

**Comment by riebling** [comment]
I believe new words aren't supported (or at least how to do it is not documented) -
I think the system only uses words currently in the dictionary/lexicon.

I'm pretty sure there's a way add them manually (at the end of the file, if each word
has an index number, just add more higher, non-conflicting index numbers?)
but we'll need to investigate how to do so automatically.

On 04/03/2016 09:34 AM, Florian Metze wrote:

> What are we doing with new words in the re-train the language model section? I.e. if I am adding new words with the new training text?
> 
> Can we add those words to the pronunciation dictionary either manually and/ or automatically?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/7

## 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by fmetze** [comment]
i have some code that does exactly that ;-)

the main idea is that
1) the user can provide an extra file with manually generated pronunciations
2) we get the missing pronunciations from the online CMU pronunciation dict
3) we may need to modify the phone set a bit
4) we compile the new dict with the right words by merging the partial dicts …

echo "**\* now let's get the (missing) pronunciations, get a dictionary ***"

# dict_phn should really be in local - but is not to avoid a conflict

rm -rf $td/x?? $td/x??.dict $td/B.bacov
awk '{print $1}' lexicon.man ${id}/dict_phn/lexicon.txt|sort -u > $td/tmptxt
diff $td/tmptxt $td/vocab|awk '/>/ {print $2}' | split -l 30000 - $td/x

for f in $( ls $td/x?? ); do
  curl -s `curl -s -F "wordfile=@$f" http://www.speech.cs.cmu.edu/cgi-bin/tools/logios/lextool.pl | awk ' /DICT/ { print $3 } '` | sed 's/ TS$/ T S/' | sed 's/ IX/ EH/g' > $f.dict
done

cat $td/x??.dict | tr 'A-Z' 'a-z' | grep '[a-z0-9]' | sort > $td/lexicon.new
cat ${id}/dict_phn/lexicon.txt|grep -v -e "^-" -e "- " | sort > $td/lexicon.old

cat lexicon.man $td/lexicon.old $td/lexicon.new|tr 'A-Z' 'a-z'|grep -v -e "<unk>" -e "[" -e "(" -e ")" -e "]" -e "^00" -e "[a-z][0-9]"|grep -v -- "-.*-"|python buildlex.py|sort|tee ${td}/lexicon-${v}.txt|awk '{print $1}' > ${td}/lexicon-${v}.v

> On Apr 4, 2016, at 9:28 AM, riebling notifications@github.com wrote:
> 
> I believe new words aren't supported (or at least how to do it is not documented) -
> I think the system only uses words currently in the dictionary/lexicon.
> 
> I'm pretty sure there's a way add them manually (at the end of the file, if each word
> has an index number, just add more higher, non-conflicting index numbers?)
> but we'll need to investigate how to do so automatically.
> 
> On 04/03/2016 09:34 AM, Florian Metze wrote:
> 
> > What are we doing with new words in the re-train the language model section? I.e. if I am adding new words with the new training text?
> > 
> > Can we add those words to the pronunciation dictionary either manually and/ or automatically?
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/7
> 
> ## 
> 
> Eric Riebling Interactive Systems Lab
> er1k@cs.cmu.edu 407 South Craig St.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/7#issuecomment-205296139

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by riebling** [comment]
I believe our [new LM building setup](https://github.com/srvk/lm_build) addresses this problem, so closing this issue

**Comment by riebling** [comment]
I believe our new [LM building setup](https://github.com/srvk/lm_build) addresses these goals:
- optional manual addition of new words
- manual supplementing of provided LM training text with adaptation text
- automatic pronunciation lookup of these new words
- automatic adding of words in training+adaptation text that are OOV w.r.t. Dictionary (and their pronunciations)

What remains is a way to inspect these automatic OOV words, manually adjust them, and iterate. The whole LM build process runs in reasonable time for now the script uses the heuristic: any word that appears more than once gets added.

There is a little more enhancement we can do, but this issue specifically (adding new words) can be closed.
