### ISSUE TITLE
8kHz version?

### ISSUE THREAD

**Issue by fmetze** [srvk/eesen-transcriber#8]
Is it possible to also run this with 8kHz models? Either by compiling it separately, or by doing both in the same VM?

**Comment by riebling** [comment]
Let's try! I bet we can use the same VM.

On 04/03/2016 09:35 AM, Florian Metze wrote:

> Is it possible to also run this with 8kHz models? Either by compiling it separately, or by doing both in the same VM?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/8

## 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by fmetze** [comment]
i think we probably want to create a different branch in the repository, then we make a few changes (re-sampling to 8kHz) and then we just need to load a different set of models (trained on switchboard), which we have, but which we cannot make available for public download, i think.

F.

> On Apr 4, 2016, at 9:29 AM, riebling notifications@github.com wrote:
> 
> Let's try! I bet we can use the same VM.
> 
> On 04/03/2016 09:35 AM, Florian Metze wrote:
> 
> > Is it possible to also run this with 8kHz models? Either by compiling it separately, or by doing both in the same VM?
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/8
> 
> ## 
> 
> Eric Riebling Interactive Systems Lab
> er1k@cs.cmu.edu 407 South Craig St.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/8#issuecomment-205296400

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University

**Comment by riebling** [comment]
8khz models now supported, so long as we remember the 'secret URL' to give folks who are entitled to download the 8k models
